#!/bin/bash
#PBS -S /bin/bash

# Choose the MCR directory according to the compiler version used
MCR=/global/software/matlab/mcr/v901

# If running on Grex, uncomment the following line to set MCR_CACHE_ROOT:
# module load mcr/mcr

echo "Running on host: `hostname`"
cd $PBS_O_WORKDIR 
echo "Current working directory is `pwd`"

echo "Starting run at: `date`" 
./run_main_spherical.sh $MCR > mycode_${PBS_JOBID}.out
echo "Job finished at: `date`"